image: openjdk:8

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build:
  stage: build
  script:
    - ./gradlew clean build

build-intellij-2020.1:
  stage: build
  script:
    - ./gradlew clean build -PintellijVersion=2020.1
