name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1

      - uses: actions/setup-java@v2.0.0
        with:
          java-version: 11
          distribution: 'adopt'

      - run: ./gradlew build

      - uses: actions/upload-artifact@v2
        with:
          path: build/distributions/*
