on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.4.2
        with:
          java-version: 1.8
      - run: ./gradlew clean build
      - uses: actions/upload-artifact@v2
        with:
          path: build/distributions/*
  
  build-intellij-2020-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.4.2
        with:
          java-version: 1.8
      - run: ./gradlew clean build -PintellijVersion=2020.2
